
api:
  jsonplaceholder:
    domain: jsonplaceholder.typicode.com
    endpoints:
      users: users
      posts: posts
      comments: comments
      albums: albums
      photos: photos
      todos: todos
#   jsonplaceholder:
#     domain: '//jsonplaceholder.typicode.com'
#     users: '/users'
#     posts: '/posts'
#     comments: '/comments'
#     albums: '/albums'
#     photos: '/photos'
#     todos: '/todos'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jsondemo
    username: postgres
    password: Jay40984692
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  
logging:
  level:
    org.springframework: DEBUG

# main:
#   allow-bean-definition-overriding: true
  # servlet:
  #   multipart:
  #     max-request-size: 10MB
  #     max-file-size: 10MB

server.port: 8091
